# Generated by Django 3.0.5 on 2020-04-29 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_object.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
            bases=(main_object.functions.ObjectAutoSlug, models.Model),
        ),
        migrations.CreateModel(
            name='MainObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('about', models.CharField(default='', max_length=200, verbose_name='About')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, default='MainObject/default.jpg', upload_to='MainObject/', verbose_name='Main Image')),
                ('date_create', models.PositiveSmallIntegerField(default=2020, verbose_name='Date Create')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Draft')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_object.Category')),
            ],
            options={
                'verbose_name': 'Main Object',
                'verbose_name_plural': 'Main Objects',
                'ordering': ['-date_published'],
            },
            bases=(main_object.functions.ObjectAutoSlug, models.Model),
        ),
        migrations.CreateModel(
            name='RankValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Value of Object Rank',
                'verbose_name_plural': 'Values of Object Rank',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
            bases=(main_object.functions.ObjectAutoSlug, models.Model),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Message')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('main_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_object.MainObject', verbose_name='main object')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_object.Review', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP')),
                ('main_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_object.MainObject', verbose_name='main object')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_object.RankValue', verbose_name='value')),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Ranks',
            },
        ),
        migrations.AddField(
            model_name='mainobject',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='main_object.Tag', verbose_name='tag1'),
        ),
        migrations.CreateModel(
            name='AdditionalObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='object_in_objects/', verbose_name='More image for Main Object')),
                ('main_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_object.MainObject', verbose_name='MainObject')),
            ],
            options={
                'verbose_name': 'Additional Object',
                'verbose_name_plural': 'Additional Objects',
            },
        ),
    ]
